schema: ./codeGeneration/generatedSchema.gql # Input file path.
documents: [
  # ./codeGeneration/generatedSchema.gql
]
generates:
  ./generatedApi.ts: # Output file path.
    plugins:
      - 'typescript'
      # - typescript-operations'
